styles:
  demo_style1:
    id: 'demo_style1'
    name: "Demo Style 1"
    sources:
      - url: https://demo.example.com/styles/basic
      - url: https://demo.example.com/styles/weather
      - url: https://demo.example.com/styles/traffic

  demo_style2:
    id: 'demo_style2'
    name: "Demo Style 2"
    sources:
      - url: https://demo.example.com/styles/terrain
        prefix: terrain_layer
      - url: https://demo.example.com/styles/poi
        prefix: points_of_interest
      - url: https://demo.example.com/styles/transport
        prefix: transport_network

  example_with_auth:
    id: 'example_with_auth'
    name: "Example Style with Authentication"
    sources:
      - url: https://example.com/api/secure-style
        auth:
          username: demo_user
          password: demo_pass
      - url: https://example.com/api/public-style
      - url: https://another-service.com/api/data
        auth:
          username: service_user
          password: service_pass