styles:
  mix_style1:
    id: 'mix_style1'
    name: "Mix Style 1"
    sources:
      - https://example.com/styles/style1

  mix_style2:
    id: 'mix_style2'
    name: "Mix Style 2"
    sources:
      - https://example.com/styles/style1
      - https://example.com/styles/style2
